#!/bin/bash
exec api/manage.py makemigrations &
exec api/manage.py migrate &
exec api/manage.py runserver 0.0.0.0:8001 &
exec app/manage.py makemigrations &
exec app/manage.py migrate &
exec app/manage.py runserver 0.0.0.0:8000

