# Generated by Django 2.2.3 on 2019-07-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createapplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='destinaton',
            new_name='destination',
        ),
    ]
