# Generated by Django 2.2.3 on 2019-07-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createapplication', '0002_auto_20190729_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='goods',
            field=models.ManyToManyField(to='createapplication.Goods'),
        ),
    ]
