# Generated by Django 2.2.3 on 2019-07-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createapplication', '0003_auto_20190729_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
